### ISSUE TITLE
Move Cookbook Gallery here?

### ISSUE THREAD

**Issue by kmpaul** [ProjectPythiaTutorials/projectpythiatutorials.github.io#1]
This repository needs to exist as a place to which the "cookbooks.projectpythia.org" subdomain will point.  However, it is currently empty, and if you go to the site:

https://cookbooks.projectpythia.org/

The content is less than inspiring.

It seems to me that the Cookbooks Gallery could move here, and the links to the Cookbooks Gallery could point to this page.

CC @jukent

**Comment by brian-rose** [comment]
I think that makes sense! Just take the content currently served at https://projectpythia.org/cookbook-gallery.html and move it here.

**Comment by jukent** [comment]
Useful links:
Portal extensions for building the gallery - https://github.com/ProjectPythia/projectpythia.github.io/tree/main/portal/_extensions
Current Portal Cookbook gallery rendered site (where we were)- 
https://projectpythia.org/cookbook-gallery.html
Current Cookbook rendered site (where we're moving to)- 
https://cookbooks.projectpythia.org/

**Comment by jukent** [comment]
Should we package the gallery generator so that we can access it easily from multiple repositories? Does it have a place in the sphinx-pythia-theme?

**Comment by kmpaul** [comment]
If the code has to be copied over and there is a lot of duplication, then perhaps we should package the gallery generator into a separate package (in the ProjectPythia org) and install it in both places.

**Comment by jukent** [comment]
That is a good idea. Right now it is just the one file. Once we have it working I will see about importing it as a package.

**Comment by kmpaul** [comment]
We now have a separate organization for the cookbooks.  I've created a mirror issue of this issue there at ProjectPythiaCookbooks/projectpythiacookbooks.github.io#1.  I'll close this issue for now and let everyone know to move the conversation of this issue to that issue.
