### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by jukent** [ProjectPythiaTutorials/projectpythiatutorials.github.io#2]
We want a landing page that we can generate a site from that will contain a table with every tutorial repository in this organization (save the template) and a link to that repository's Binder.

Perhaps we want this in a new repository within the ProjectPythiaTutorials organization, and we want to move the current`README.md` from ProjectPythiaTutorials/tutorial-template#1 there as well (and replace it with the `README_template.md`). Thoughts?

**Comment by jukent** [comment]
Sounds like we want to add a page to the main Pythia portal that pulls in repositories from this organization, rather than go this method.

**Comment by kmpaul** [comment]
Yeah.  For now, let's do that.  We can close this and reopen it later, if we want to do that.
